### ISSUE TITLE
What to do now ? The install button is grey out !

### ISSUE THREAD

**Issue by HuyHung1408** [BlkDev9/Notes#1]
![image](https://user-images.githubusercontent.com/86362423/128511084-03374c8f-3864-4997-8d55-7b8bc07fc217.png)

**Comment by BlkDev9** [comment]
this is because i don't have a certificate to sign the app, i'm searching a way to fix this

**Comment by BlkDev9** [comment]
For now the only way is to go into settings and set developer mode to install the app without certification

**Comment by HuyHung1408** [comment]
Ok thanks a lot

**Comment by BlkDev9** [comment]
also i'm uploading a new update with new features as picture in picture

**Comment by HuyHung1408** [comment]
I'm waiting for it

**Comment by BlkDev9** [comment]
Now Released!

**Comment by HuyHung1408** [comment]
ok, nice

**Comment by HuyHung1408** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/86362423/128521688-080933a3-96da-4c78-8d71-386f4c27c86b.png)

**Comment by HuyHung1408** [comment]
![image](https://user-images.githubusercontent.com/86362423/128521940-4852161f-493c-472b-8ecd-5d3527679006.png)
I already install the certificate

**Comment by BlkDev9** [comment]
Ok now try to install the app or even better the new 0.1.8 update with print function and crash fixes!

**Comment by HuyHung1408** [comment]
ok thanks

**Comment by HuyHung1408** [comment]
![image](https://user-images.githubusercontent.com/86362423/128530856-c92281bb-23af-45fa-9906-3decd90156f7.png)
![image](https://user-images.githubusercontent.com/86362423/128530936-117754b3-1b33-4c43-b64d-e885f424eeaf.png)

**Comment by BlkDev9** [comment]
Nice!
