### ISSUE TITLE
Icon disappear in 0.2.5. I don't know if this is a bug or any other thing

### ISSUE THREAD

**Issue by HuyHung1408** [BlkDev9/Notes#3]
![image](https://user-images.githubusercontent.com/86362423/128637304-67ffc51d-fea3-435a-afe1-de36bde51bea.png)

**Comment by BlkDev9** [comment]
Thanks for the Feedback, i'm working on the next update and i'm trying to fix this, i noticed this even on my laptop but strangely not on the Desktop

**Comment by BlkDev9** [comment]
Also a little spoiler:
I created (somehow in blender 3d) a icon for the app, it was the default notepad icon before but if i ever want to make this project bigger i needed a personal Icon

**Comment by BlkDev9** [comment]
![Icon](https://user-images.githubusercontent.com/86930621/128639968-2f257405-0d4a-4102-a4f1-505b4686a754.png)

**Comment by HuyHung1408** [comment]
Nice

**Comment by BlkDev9** [comment]
in the new update the problem seems fixed, thanks a lot for the support!
