### ISSUE TITLE
File and View not go back to original place after go full screen

### ISSUE THREAD

**Issue by HuyHung1408** [BlkDev9/Notes#4]
https://user-images.githubusercontent.com/86362423/129480530-47bf4b71-7689-4d75-a949-3b83c0bc9040.mp4

**Comment by BlkDev9** [comment]
this happens when using the upper button instead of the button inside the view menu, i'm looking into this, thanks a lot for the feedback!

**Comment by HuyHung1408** [comment]
the new one was fixed so I will close this for now, good job !
