### ISSUE TITLE
Notes is not installing in Windows 11

### ISSUE THREAD

**Issue by Alloyd854** [BlkDev9/Notes#5]
Hi. I can't install the Notes app in Windows 11. How to fix this?

**Comment by HuyHung1408** [comment]
How did you install the app? Error with certificate?

**Comment by HuyHung1408** [comment]
https://user-images.githubusercontent.com/86362423/133030550-742937d2-b0d0-4df2-82c9-25a0e3010222.mp4

Some packages I already install so it will show errors. Everything else is the same with Windows 11.

**Comment by Alloyd854** [comment]
This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)

**Comment by Alloyd854** [comment]
Thanks! Now it's working.
