### ISSUE TITLE
Context menu on RichEditBox not translated in English.

### ISSUE THREAD

**Issue by Alloyd854** [BlkDev9/Notes#6]

**Comment by HuyHung1408** [comment]
I think we have to wait for him to change this lol. It has been a month since the last time he updated the app. I don't know if he still continues. But I hope he still continues, this app is good anyway.

**Comment by BlkDev9** [comment]
Sooo... yeah i kinda stopped working on this, but these days i secretly started again, worked on file support, so you can set the app as the default app, fixed lots of crashes and made a new Icon + new icon for document .txt, .rtf. fixed some little bugs, and i'm aiming at Translations, so the app can be used by everyone!!

**Comment by BlkDev9** [comment]
![icon](https://user-images.githubusercontent.com/86930621/133141924-391e9b30-b576-4b41-8ef8-210b05ff5cea.png)
App icon

![iconus](https://user-images.githubusercontent.com/86930621/133142272-c9eed53f-2499-4cc7-8a84-3cf7e91cc5d0.png)
Txt document icon

they are both made in Blender3D

**Comment by HuyHung1408** [comment]
Nice, I'm wating for this

**Comment by HuyHung1408** [comment]
But I think it's missing the certificate to run the app lol.

**Comment by BlkDev9** [comment]
Really!? I think i forgot, later i will post a fix

**Comment by HuyHung1408** [comment]
Ok, thanks

**Comment by BlkDev9** [comment]
Just fixed the problem, i was dumb so i forgot to add the certificate

**Comment by BlkDev9** [comment]
btw if you guys need the open txt file as default app, you need to set the app as trusted under privacy/file system and activate the app

**Comment by BlkDev9** [comment]
also this problem is fixed in 0.4.0 so this problem is now closed!
