### ISSUE TITLE
Can you add a suggestion box in font? 

### ISSUE THREAD

**Issue by HuyHung1408** [BlkDev9/Notes#7]
![Screenshot 2021-09-16 074015](https://user-images.githubusercontent.com/86362423/133531436-0c5986d2-685f-4cbc-845a-5eb96182d60a.png)
Like this!

**Comment by BlkDev9** [comment]
It is in the next features i want to add! Maybe i should do some research before, because i honestly don't know how to make a font suggestion box, but i will learn!

**Comment by HuyHung1408** [comment]
Ok, nice thanks

**Comment by BlkDev9** [comment]
Fun fuct,,, the new update is about to release... guess what i added?

**Comment by HuyHung1408** [comment]
I just try it out, and it looks freaking good.
